sudo: required

language: php
php:
  - 5.6

# Sample to be able to skip temporarily some items, but still executing them
#matrix:
#  allow_failures:
#    - php: 5.6
#      env: BUILD_CLIENT=1

env:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1
    BUILD_SERVER=1
  - CODE_REVIEW=1
    REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1
    REVIEW_STANDARD="DrupalPractice"

services:
  - docker

before_install:
  - composer self-update
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - sudo pip install docker-compose
  - openssl aes-256-cbc -K $encrypted_b2dc5bc8fb77_key -iv $encrypted_b2dc5bc8fb77_iv -in gdrive-service-account.json.enc -out gdrive-service-account.json -d

install:
  - $TRAVIS_BUILD_DIR/ci-scripts/install_client.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/install_server.sh

before_script:
  - $TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh

script:
  - $TRAVIS_BUILD_DIR/ci-scripts/test_client.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/test_server.sh

cache:
  directories:
    - client/elm-stuff/packages
    - client/sysconfcpus
