sudo: require

language: php
php:
  - 5.6

env:
  - BUILD_SERVER=1
  - BUILD_CLIENT=1
  - BUILD_WEBDRIVERIO=1
    BUILD_SERVER=1
  - CODE_REVIEW=1
    REVIEW_STANDARD="Drupal"
  - CODE_REVIEW=1
    REVIEW_STANDARD="DrupalPractice"

services:
  - docker

cache:
  directories:
    - sysconfcpus

before_install:
  - composer self-update
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - curl -L "https://github.com/docker/compose/releases/download/1.11.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

install:
  - $TRAVIS_BUILD_DIR/ci-scripts/install_client.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/install_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/install_server.sh

before_script:
  - $TRAVIS_BUILD_DIR/ci-scripts/prepare_client.sh

script:
  - $TRAVIS_BUILD_DIR/ci-scripts/test_client.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/test_coder.sh
  - $TRAVIS_BUILD_DIR/ci-scripts/test_server.sh

cache:
  directories:
    - client/elm-stuff/packages
    - client/sysconfcpus
