version: '2'
services:
    hub:
        privileged: true
        image: elgalu/selenium
        environment:
          - USE_SELENIUM=2
          - VIDEO=true
          - FFMPEG_FRAME_RATE=25
          - SCREEN_WIDTH=1024
          - SCREEN_HEIGHT=768

    server.local:
        privileged: true
        image: server
        environment:
            - BUILD_WEBDRIVERIO
            # This above means that we pass it from the shell env.

